### ISSUE TITLE
Problem on startup ...

### ISSUE THREAD

**Issue by mohierf** [shinken-monitoring/mod-import-glpi#1]
When Shinken is started as a service when system starts, no requests are sent by arbiter to get data from DB ... do not know why, but it is a fact that only local Shinken configuration is considered.

Moreover, restarting Shinken with WS arbiter is not functionning ...

To be investigated ...

**Comment by ddurieux** [comment]
You have right mysqldb python modul installed?

**Comment by mohierf** [comment]
Yes. I ''apt-get install python-mysqldb'' ...

**Comment by ddurieux** [comment]
Works nicely for me.
Have you debug log of arbiter?

**Comment by mohierf** [comment]
Arbiter do not start in debug mode when started as a service ... what I noticed is that the receiver is not started on system startup. I will try to make it start and to make Shinken start all modules in debug mode !

**Comment by mohierf** [comment]
Obsolete ... :-)
