### ISSUE TITLE
If tags is unset in glpi, object from root entity are loaded

### ISSUE THREAD

**Issue by camlafit** [shinken-monitoring/mod-import-glpi#9]
Hi

In my import-glpi configuration I set : 
- tags toto
  In my glpi any entity is associated with this tag

My result all object in Root Entity are loaded.

If I affect this tag to one glpi entity, in this case only object from this entity are loaded. Behavior looks correct.

**Comment by mohierf** [comment]
I do not understand what the problem is ... if you declare a tag in the module configuration and that this tag is not attached to any Glpi entity, you will get all the Root entity objects. It is the expected behavior.

**Comment by camlafit** [comment]
Hi

Yes sorry I've forgot an information. User account set in import glpi is
affected only to sub entity. He couldn't get any Entity root hosts in this
case.

**Comment by mohierf** [comment]
User account used by the `import-glpi` module should be member of the root entity if you want to be able to get elements located in the root entity ... perharps an extra information in the module documentation should be interesting :wink:

**Comment by camlafit** [comment]
Hi

In my use case, I've one glpi with some entities. I need to deploy a
shinken to a specific sub entity. And sub entity users are not allowed to
see information outside their sub entity.
Then I use a sub entity user to get information from glpi.
In this case, we must not provide information outside his entity.
